### ISSUE TITLE
the chunking is not chunking??

### ISSUE THREAD

**Issue by JediMonkeyDan** [thedefaultman/dropbox-large-file-uploader#2]
{"error_summary": "lookup_failed/incorrect_offset/..", "error": {".tag": "lookup_failed", "lookup_failed": {".tag": "incorrect_offset", "correct_offset": 0}}}

error message says the correct offset should be 0 but the initial value is literally 0 lol.

**Comment by thedefaultman** [comment]
it's chunking now
